pipeline {

    agent any

    tools {
    // Specify the Gradle installation by name
    gradle 'Gradle 7.6.1'
    jdk 'Java17'    
  }

    environment {
        DOCKER_TAG = getDockerTag()
        NEXUS_URL  = '172.32.5.240:5050'
        IMAGE_URL_WITH_TAG = "${NEXUS_URL}/loan-trx-manager:${DOCKER_TAG}"
    }

    stages {

        stage('Gradle build') {
            steps {
                sh 'gradle build -x test'
            }
        }
        stage('Building Docker Image') {
            steps {
                sh "docker build . -t ${IMAGE_URL_WITH_TAG}"
            }
        }
        stage('Push to In-house Nexus Docker Registry') {
            steps {
                withCredentials([string(credentialsId: 'nexus-pwd', variable: 'nexusPwd')]) {
                    sh 'docker login -u admin -p ${nexusPwd} ${NEXUS_URL}'
                    sh "docker push ${IMAGE_URL_WITH_TAG}"
                }
            }
        }
        stage('Sending Deployment Artifacts to credit-pro-linux') {
            steps {
                sh 'chmod +x changeTag.sh'
                sh "./changeTag.sh ${DOCKER_TAG}"

                sshPublisher(publishers: [sshPublisherDesc(configName: 'credit-pro-linux', transfers: [sshTransfer(cleanRemote: false, excludes: '', execCommand: '', flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: '/pipelines/loan-trx-manager/', remoteDirectorySDF: false, removePrefix: '', sourceFiles: '*.yml')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: false)])                
            }
        }

        stage('Deployment of service in credit-pro-linux') {
            steps {
               sshPublisher(publishers: [sshPublisherDesc(configName: 'credit-pro-linux', transfers: [sshTransfer(cleanRemote: false, excludes: '', execCommand: 'docker-compose -f /home/chtemba/pipelines/loan-trx-manager/docker-compose.yml up -d', flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: '', remoteDirectorySDF: false, removePrefix: '', sourceFiles: '')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: false)])
            }
        }
    }
}

def getDockerTag() {
    def tag  = sh script: 'git rev-parse HEAD', returnStdout: true
    return tag
}